Cargo.lock
Cargo.toml
src/api/darwinia.rs
src/api/mod.rs
src/config.rs
src/listener.rs
src/service/ethereum.rs
src/service/guard.rs
src/service/mod.rs
src/service/redeem.rs
src/service/relay.rs
src/service/subscribe/mod.rs

+ Add sudo call and council call
+ Complete guard service

Complete guard service

---

Cargo.lock
primitives/Cargo.toml
primitives/src/array.rs
primitives/src/byte.rs
primitives/src/chain/ethereum/block.rs
primitives/src/chain/ethereum/receipt.rs

bridger cannot be published to crates.io since some git-dependencies used.
Remove them and use some other dependencies from crates.io.

repair publish to crates.io

---

Cargo.toml
darwinia/Cargo.toml

the lower version of jsonrpsee client will report an error when connecting to `pc2-rpc-xxx` ws address.
upgrade jsonrpsee-ws-client from 0.2.0-alpha.2 to 0.2.0-alpha.3
```toml
[dependencies]
jsonrpsee-ws-client = "0.2.0-alpha.3"
jsonrpsee-types = "0.2.0-alpha.2"
[dependencies.tokio]
package = "tokio"
version = "0.2.22"
features = ["full"]
```
only need to upgrade ws client

chore: upgrade jsonrpsee ws client to fix wrong report error on valid ws address

---

.maintain/config/linked-darwinia.toml
.maintain/config/task-darwinia-ethereum.toml
components/client-darwinia-subxt/src/config.rs
task/task-darwinia-ethereum/docs/Guide.md
task/task-darwinia-ethereum/src/config.rs

By the default, in darwinia-ethereum, the darwinia crypto is always enabled. this may conflict with the configuration definition of [task](https://github.com/darwinia-network/bridger/blob/d25c211a22fae9fd3c24fcead136940deca7a6b9/task/task-darwinia-ethereum/src/config.rs#L44-L46). so add `enable_crypto` in [darwinia](https://github.com/darwinia-network/bridger/blob/d25c211a22fae9fd3c24fcead136940deca7a6b9/components/client-darwinia-subxt/src/config.rs#L6-L8) block.
Examples:
before
```toml
[darwinia]
endpoint = "ws://127.0.0.1:9944"
relayer_private_key = "<RAW KEY>"
[task]
enable_crypto = false
```
If configured like this, there will be conflicts, because [BridgeCrypto](https://github.com/darwinia-network/bridger/blob/d25c211a22fae9fd3c24fcead136940deca7a6b9/supports/support-proc-macro/src/ …

darwinia support control enable_crypto manually

---

task/task-darwinia-ethereum/src/service/starter.rs

Sometimes the starter service starts too early (no enable crypto).
```text
[2021-08-04T14:44:54Z DEBUG lifeline::dyn_bus::storage] DarwiniaLinkedMessage linked in DarwiniaLinkedBus
[2021-08-04T14:44:54Z DEBUG lifeline::spawn] START ExtrinsicService/linked-darwinia-service-extrinsic
[2021-08-04T14:44:54Z DEBUG lifeline::dyn_bus::storage] BridgeState stored in DarwiniaEthereumBus
[2021-08-04T14:44:54Z DEBUG lifeline::dyn_bus::storage] DarwiniaEthereumMessage linked in DarwiniaEthereumBus
[2021-08-04T14:44:54Z DEBUG lifeline::spawn] START StarterService/task-darwinia-ethereum-service-starter
[2021-08-04T14:44:54Z DEBUG lifeline::spawn] START DarwiniaLinkedBus/task-darwinia-ethereum-carry-linked-darwinia
[2021-08-04T14:44:54Z DEBUG lifeline::dyn_bus::storage] PangolinMillauMessageSend linked …
```

fix start too early

---

bin/src/initialize.rs

We can set custom log level when use binary.
```bash
RUST_LOG=bridge=info,task-darwinia-ethereum=info,task-pangolin-ropsten=info \
bridger server \
--host 127.0.0.1 \
--port 1098 \
--base-path /path/to/config
```

Support custom log level

---

components/client-pangolin-subxt/src/darwinia/runtime.rs

```
[2021-11-01T08:50:59Z ERROR task_pangolin_ropsten::service::pangolin] An error occurred while processing the events of block 1100616: Type size unavailable while decoding event: "SpecVersion"
Stack backtrace:
0: task_pangolin_ropsten::service::pangolin::DarwiniaServiceRunner::start::{{closure}}
1: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2: <lifeline::spawn::LifelineFuture<F> as core::future::future::Future>::poll
3: tokio::runtime::task::harness::Harness<T,S>::poll
4: std::thread::local::LocalKey<T>::with
5: tokio::runtime::thread_pool::worker::Context::run_task
6: tokio::runtime::thread_pool::worker::Context::run
7: tokio::macros::scoped_tls::ScopedKey<T>::set
8: tokio::runtime::thread_pool::worker::run
9: …
```

Add missing type size for `SpecVersion`

---

Cargo.lock
bin/src/initialize.rs
components/client-pangolin-subxt/Cargo.toml
components/ethereum/src/ethereum/client.rs
components/shadow/src/shadow.rs
primitives/src/error.rs
supports/support-ethereum/src/block.rs
supports/support-ethereum/src/parcel.rs
supports/support-ethereum/src/receipt.rs
task/task-pangolin-ropsten/Cargo.toml
task/task-pangolin-ropsten/src/service/extrinsics/mod.rs

Close #311 
```
[2021-11-17T15:31:53Z TRACE task_pangolin_ropsten::service::affirm::handler] The last confirmed ethereum block is 11227811
[2021-11-17T15:31:53Z TRACE task_pangolin_ropsten::service::affirm::handler] The last relayed ethereum block is 11227811
[2021-11-17T15:31:53Z TRACE task_pangolin_ropsten::service::affirm::handler] Your are affirming ethereum block 11410948
[2021-11-17T15:31:54Z TRACE task_pangolin_ropsten::service::redeem::handler] Try to redeem ethereum tx "0x902082fbbb4e070b4d3225a9263099591bdfa23b90ac2c421c894c1d9f197b35"...
[2021-11-17T15:31:54Z TRACE task_pangolin_ropsten::service::affirm::handler] Prepare to affirm ethereum block: 11410948
[2021-11-17T15:31:54Z TRACE task_pangolin_ropsten::service::pangolin::pangolin_tracker] Track pangolin block: 1323270 …
```

Fix failed to send affirm extrinsics

---

task/task-darwinia-crab/src/chains/crab.rs
task/task-darwinia-crab/src/chains/darwinia.rs

Fix wrong client

---

frame/bin/Cargo.toml
frame/bin/src/command/handler/registry.rs
frame/bin/src/command/types/registry.rs
frame/bin/src/config.rs
frame/bin/src/external/provider/precompiled_binary.rs

Closes #394 
Usage
```
bridger registry version                # Show current version
bridger registry version 0.5.1       # Set registry version to 0.5.1
bridger registry version --bundle # Set bundle version to config
```
```
$ ./bridger.sh pangolin-ropsten --version
+ cargo build --manifest-path /dev/bridger/frame/Cargo.toml --package darwinia-bridger
Finished dev [unoptimized + debuginfo] target(s) in 0.47s
+ /dev/bridger/frame/target/debug/bridger pangolin-ropsten --version
2022-01-11 09:21:47 DEBUG bridger: Found subcommand (pangolin-ropsten) and args: --version
2022-01-11 09:21:47 TRACE bridger: Try execute external command
Try execute bridge-pangolin-ropsten@0.5.0
2022-01-11 09:21:47 TRACE bridger: Force mode: false
2022-01-11 09:21:47 TRACE bridger: Download package path is: …
```

Custom registry version to support download bridge with custom version

---

.github/workflows/subgraph-dev.yml
.github/workflows/subgraph-prod.yml
.github/workflows/subquery-dev.yml
.github/workflows/subquery-prod.yml
subql/darwinia/schema.graphql

Closes #393 
**Develop**
When `subsql/<CHAIN>/schema.graphql` changed, will delete the old stage deployment and create a new stage deployment, this will delete all saved data in Subquery.
If the schema does not changes, just redeploy it. the saved data will keep.
⚠️ ⚠️ ⚠️  Only trigger the in pull request and the base branch is `master`, PLEASE DON'T PUSH CODE TO MASTER BRANCH DIRECTLY.
**Production**
Trigger when creating a new tag.
1. Promote last stage deployment to production deployment.
2. Create a new stage deployment force.
⚠️ ⚠️ ⚠️ Before creating a tag you need to confirm the stage deployment is scan completed.

Subquery ci

---

bridges/darwinia-ethereum/Cargo.lock
bridges/darwinia-ethereum/bridge/Cargo.toml
bridges/darwinia-ethereum/client-darwinia/Cargo.toml
bridges/pangolin-ropsten/Cargo.lock
bridges/pangolin-ropsten/bridge/Cargo.toml
bridges/pangolin-ropsten/client-pangolin/Cargo.toml

Following upstream, the substrate-subxt project is renamed to subxt.

Rename substrate-subxt to subxt

---

frame/supports/support-command-kv/src/schema.toml

Missing affirm.relayed types
```
2022-03-10 06:17:08 ERROR pangolin-ropsten: [ropsten] [affirm] affirm err: KVError::KVError: invalid type: string "12062166", expected u64 chain="ropsten" action="affirm"
```

Defined affirm.relayed types

---

.github/workflows/subquery-dev.yml
.github/workflows/subquery-prod.yml

https://github.com/darwinia-network/bridger/runs/5549312340?check_suite_focus=true#step:6:38
https://github.com/fewensa/subquery-cli/commit/fe0820720c34774d0d69df9c5692754dcc4407d8
An idea: maybe the subquery cli can be wrapped into action for other repositories to use

Fix deploy to subquery

---

bridges/pangoro-kiln/bridge/src/kiln_client/client.rs
bridges/pangoro-kiln/bridge/src/kiln_client/types.rs
bridges/pangoro-kiln/bridge/src/pangoro_client/client.rs
bridges/pangoro-kiln/bridge/src/service/header_relay/kiln_to_pangoro.rs

Bridger will only relay one header to light client, if there are many periods missed, which implements this strategy: #488 .

Update header relay strategy

---

.github/workflows/ci.yml
bridges/pangolin-pangolinparachain/bridge/src/command/types.rs
frame/assistants/client-crab-parachain/src/fastapi/bridge_s2s/bridge_crab.rs
frame/assistants/client-crab-parachain/src/fastapi/bridge_s2s/generic.rs
frame/assistants/client-crab/src/fastapi/bridge_s2s/bridge_crabparachain.rs
frame/assistants/client-crab/src/fastapi/bridge_s2s/bridge_darwinia.rs
frame/assistants/client-darwinia/src/fastapi/bridge_s2s/bridge_crab.rs
frame/assistants/client-kusama/src/fastapi/bridge_s2s/generic.rs
frame/assistants/client-pangolin-parachain/src/fastapi/bridge_s2s/bridge_pangolin.rs
frame/assistants/client-pangolin-parachain/src/fastapi/bridge_s2s/generic.rs
frame/assistants/client-pangolin/src/fastapi/bridge_s2s/bridge_pangolinparachain.rs
frame/assistants/client-pangolin/src/fastapi/bridge_s2s/bridge_pangoro.rs
frame/assistants/client-pangoro/src/fastapi/bridge_s2s/bridge_pangolin.rs
frame/assistants/client-rococo/src/fastapi/bridge_s2s/generic.rs
frame/assistants/shadow-liketh/tests/test_shadow.rs

Do some tests and fix s2s bridge bug.
fix https://github.com/darwinia-network/bridger/issues/510

Fix s2s bridge

---

.maintain/config/bridge-darwinia-ethereum.toml

Remove `//Alice` hinting, which wrongly implies mnemonic phrase, and replace it with more straightforward wording.

Update darwinia-ethereum bridge guide

---

.github/workflows/staging.yaml
assistants/client-crab/tests/test_component.rs

Currently Darwinia not upgrade to 2.0, will be open when bridge fixed

Disable bridge darwinia-crab for staging ci

---

assistants/bin-e2e/src/bridge.rs
assistants/bin-e2e/src/service/header_relay/beacon_header_relay.rs
assistants/bin-e2e/src/service/header_relay/mod.rs
assistants/bin-e2e/src/service/message_relay/darwinia_to_eth.rs
assistants/bin-e2e/src/service/message_relay/eth_to_darwinia.rs
assistants/client-contracts/src/beacon_light_client.rs
assistants/client-contracts/src/inbound.rs
assistants/relay-e2e/src/header/eth_beacon_header_relay.rs
assistants/relay-e2e/src/message/darwinia_message_client.rs
assistants/relay-e2e/src/message/ethereum_message_client.rs
assistants/relay-e2e/src/message/message_relay_runner.rs
bridges/pangolin-goerli/bridge/tests/test_web3.rs
traits/bridge-e2e/src/client.rs

Change the strategy of Eth header relay:
- The header will be relayed from Ethereum to Darwinia when the message delivery or confirmation services notify it.
- If there are no messages needed to relay, header relay service will work only once every period(32*256 blocks)
Tests:
- Eth light client contract on Pangolin: https://pangolin.subscan.io/evm_transaction?block=0x9Ca2b190d84E635F131060319FACc943b0653680&page=1
Relayer account:
1. https://goerli.etherscan.io/address/0x573749FFee40b3aA6C080144D4071847c51B5C33
2. https://goerli.etherscan.io/address/0xa4A07c23C6e3b3835DC760563E898143c23704Ae

On demand header relay

---

.github/workflows/staging.yaml
assistants/bin-s2s/src/bridge/config/generic.rs
assistants/bin-s2s/src/service/para_with_para/header/source_to_target/parachain_parahead_relay.rs
assistants/bin-s2s/src/service/para_with_para/header/source_to_target/relaychain_grandpa_relay.rs
assistants/client-kusama/src/fastapi/common/mod.rs
assistants/client-moonbase/src/fastapi/common/mod.rs
assistants/client-polkadot/src/fastapi/common/mod.rs
assistants/client-rococo/src/fastapi/common/mod.rs
assistants/feemarket-s2s/src/relay/basic.rs
assistants/relay-e2e/src/ecdsa/ecdsa_scanner.rs

- Enable more bridge to staging CI build
- Code clean and Lint
- Change s2s bridge feemarket strategy, check timeout first, fix assigned relayer not relay timeout order bug.

Bridge pangolin-pangoro code clean and update feemarket strategy
