Cargo.lock, Cargo.toml, README.md, src/api/darwinia.rs, src/api/shadow.rs, src/cmd/confirm.rs, src/cmd/mod.rs, src/service/ethereum.rs, src/service/guard.rs, src/service/redeem.rs, src/service/relay.rs
Adapts the new relayer game API
=> Adapts the new relayer Game

src/api/darwinia.rs, src/cmd/run.rs, src/listener.rs
=> Refactor run and add more startup info

src/service/redeem.rs
=> Fix the problem of redeem failure caused by sending too fast

src/cmd/guard.rs, src/cmd/mod.rs, src/cmd/run.rs, src/service/guard.rs
=> Guard role checking fix and guard subcommand

src/api/darwinia.rs, src/api/mod.rs, src/cmd/run.rs, src/service/guard.rs
=> fix guard not working if the account is both a sudo and a t-c member

src/api/darwinia.rs, src/cmd/mod.rs, src/cmd/run.rs, src/service/guard.rs
1. extract signer and real's same logic
2. add proxy to vote call
=> Add proxy to vote

.github/workflows/release.yml
=> Add GitHub Actions to publish the package on crates.io.

primitives/src/chain/ethereum/header.rs, primitives/src/chain/ethereum/parcel.rs, src/cmd/affirm.rs, src/cmd/affirm_raw.rs, src/cmd/mod.rs, src/cmd/show_parcel.rs
=> Subcmds `show-parcel` and `affirm-raw`

primitives/src/chain/ethereum/parcel.rs, src/service/ethereum.rs, src/service/redeem.rs, src/service/relay.rs
=> Fix try_lock fail possibilities

.maintain/Dockerfile
=> Install ca-certificates in the Docker image.

src/cmd/mod.rs, src/cmd/run.rs
Closing #67, checking if bridger runs.
=> Printing version as top log of command run

Cargo.lock, primitives/Cargo.toml, primitives/src/result.rs, primitives/src/rpc/ethereum/mod.rs, src/api/darwinia.rs, src/api/shadow.rs, src/cmd/run.rs, src/config.rs, src/error.rs, src/service/ethereum.rs, src/service/guard.rs, src/service/redeem.rs, src/service/relay.rs, src/service/subscribe/mod.rs
1. for low-level errors, error! detailed source error info
2. for business abnormal errors, warn! error message mostly
=> Classifying errors to process separately

src/api/shadow.rs, src/error.rs, src/service/ethereum.rs
companion of  [shadow#116](https://github.com/darwinia-network/shadow/pull/116)
=> Parent mmr root & error response handling. companion of shadow#116

Cargo.lock, primitives/Cargo.toml, primitives/src/chain/ethereum/block.rs, primitives/src/chain/ethereum/header.rs, primitives/src/chain/ethereum/mod.rs, primitives/src/chain/ethereum/receipt.rs, primitives/src/rpc/ethereum/block.rs, primitives/src/rpc/ethereum/mod.rs, primitives/src/rpc/ethereum/receipt.rs, primitives/src/rpc/mod.rs
bridger-primitives need to support an API for getting receipt information.
for issue https://github.com/darwinia-network/shadow/issues/114
=> add receipt api

Cargo.lock, primitives/src/frame/bridge/relay_authorities.rs, src/api/darwinia.rs
companion of [darwinia-common#438](https://github.com/darwinia-network/darwinia-common/pull/438)
=> Do not submit mmr-root

src/api/darwinia_sender.rs, src/service/subscribe/mod.rs
=> Fix the bug of re sending delayed extinsics. 

primitives/src/frame/bridge/relay_authorities.rs, primitives/src/frame/ethereum/backing.rs, src/api/darwinia.rs, src/service/extrinsics.rs, src/service/subscribe/mod.rs
companion of [darwinia-common#447](https://github.com/darwinia-network/darwinia-common/pull/447)
=> Refactor relay authorities

README.md
@HackFisher @wuminzhe Please take a look, see if there's anything I should add or remove.
=> Add docs for D2E relay.

Cargo.lock, src/api/darwinia_sender.rs
=> Consider proxy when ecdsa signing

src/api/darwinia.rs, src/api/darwinia_sender.rs, src/cmd/guard.rs, src/cmd/run.rs, src/cmd/set_darwinia_start.rs, src/service/subscribe/mod.rs, src/tools.rs
=> Fix roles checking

src/api/ethereum.rs
=> Get gas price from gasnow

.github/workflows/ci.yml, .gitignore, .maintain/Dockerfile, Cargo.lock, Cargo.toml, darwinia/Cargo.toml, darwinia/src/darwinia.rs, darwinia/src/rpc/header_mmr.rs, primitives/Cargo.toml, primitives/src/array.rs, primitives/src/chain/ethereum/block.rs, primitives/src/chain/ethereum/ethash.rs, primitives/src/chain/ethereum/mmr.rs, primitives/src/chain/ethereum/parcel.rs, primitives/src/chain/ethereum/proof.rs, primitives/src/chain/ethereum/receipt.rs, primitives/src/lib.rs, primitives/src/rpc/ethereum/mod.rs, primitives/src/rpc/mod.rs, src/api/shadow.rs, src/cmd/info_d2e.rs, src/config.rs, src/service/guard.rs, src/service/redeem.rs
With PR: https://github.com/darwinia-network/substrate-subxt/pull/1
=> Bump `jsonrpsee` dependency

primitives/src/frame/bridge/relay_authorities.rs
if the return value is an Option type, we must define it in macro
=> fix return type bug

Cargo.lock, supports/support-proc-macro/Cargo.toml
Update support-proc-macro crate version same with bridger
=> Bump version to 0.4.0

Cargo.lock, primitives/src/crypto.rs, supports/support-ethereum/src/block.rs, task/task-darwinia-ethereum/src/service/ethereum/ethereum_logs_handler.rs, task/task-darwinia-ethereum/src/service/extrinsics.rs, task/task-darwinia-ethereum/src/service/guard.rs, task/task-darwinia-ethereum/src/service/relay.rs, task/task-pangolin-ropsten/src/route.rs, task/task-pangolin-ropsten/src/service/ethereum/ethereum_logs_handler.rs, task/task-pangolin-ropsten/src/service/extrinsics.rs, task/task-pangolin-ropsten/src/service/guard.rs, task/task-pangolin-ropsten/src/service/relay.rs, task/task-pangolin-ropsten/src/task.rs
=> Pangolin ropsten

task/task-darwinia-ethereum/src/service/darwinia/mod.rs, task/task-darwinia-ethereum/src/service/ethereum/mod.rs, task/task-pangolin-ropsten/src/service/darwinia/mod.rs, task/task-pangolin-ropsten/src/service/ethereum/mod.rs
issue:  https://github.com/darwinia-network/bridger/issues/228
=> fix channel closed error

Cargo.lock
```text
[2021-08-13T03:20:58Z DEBUG support_s2s::runner::pangolin_millau::init] source client -> Client { genesis_hash: 0x84dd1708a20cb41a1fc6bf6935baacfc692cb534fd3d4bef57e945b39366b02a }
[2021-08-13T03:20:58Z DEBUG support_s2s::runner::pangolin_millau::init] target client -> Client { genesis_hash: 0x99b9053533c5dc4fca17fb46131a61b4e8c87ec48fada4d842abfc41ef70b582 }
[2021-08-13T03:21:00Z INFO  support_s2s::relay::headers_initialize] Prepared initialization data for Millau-headers bridge at Pangolin: InitializationData { header: Header { parent_hash: 0x9d6a4311b9652c829ac391cbd882aaef77eb1ea685f00053c5bf1403ceb98a2f, number: 125, state_root: 0x158d3869590c6329b32edad36db60fd8d0b9c05a3c95764e8622696347ed1595, extrinsics_root: 0x34834eb0fd98a5a9ffc4df0bbf5a194413cc917011c12d9b1d87dbcae70d79b …
```
=> Update dependencies, fix millau to pangolin init bridge

task/task-pangolin-pangoro/docs/Guide.md, task/task-pangolin-pangoro/docs/Guide_zh_CN.md
Add how to buld `pangolin` and `pangoro`. and public chains endpoint
=> pangolin-pangoro docs

.github/workflows/ci.yml, .github/workflows/staging.yml
Build docker image when push code to master branch
=> [ci] build staging docker image

components/client-darwinia-subxt/src/darwinia/runtime.rs, components/client-pangolin-subxt/src/darwinia/runtime.rs
Add `TsInMs` type size
pangolin: https://github.com/darwinia-network/darwinia-common/blob/bf906628f8df560f1cf060739647a1340e3884fe/node/runtime/pangolin/types.json#L42
darwinia: https://github.com/darwinia-network/darwinia/blob/a965cd8d2c48e98644b0edbffe846f31cbfb3f6f/runtime/darwinia/types.json#L42
=> fix `TsInMs` type size

task/task-pangolin-pangoro/src/chains/pangolin.rs, task/task-pangolin-pangoro/src/chains/pangoro.rs
fix pangolin-pangoro messages relay bug
https://pangolin.subscan.io/extrinsic/511218-2
=> fix invalid proof for messages relay

.maintain/config/task-pangolin-pangoro.toml
Related:
https://github.com/darwinia-network/darwinia-common/pull/832
=> Update default lane id

task/task-pangolin-pangoro/src/message.rs, task/task-pangolin-pangoro/src/route.rs, task/task-pangolin-pangoro/src/service/relay.rs, task/task-pangolin-pangoro/src/task.rs, task/task-pangolin-pangoro/src/types.rs, task/task-pangolin-ropsten/src/service/redeem.rs
Remove select_bridge macro, direct messages-relay between pangolin and pangoro.
=> Simplify messages-relay

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/staging.yml, supports/support-ethereum/src/block.rs
- Use latest nightly version
- Fix staging build https://github.com/darwinia-network/bridger/pull/323/commits/fdea054459b322e26763735e937191c533da8963
=> Update rust toolchain

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/staging.yml
- Use bz2 instead zstd
- Set `rust:1` to base image
=> Improve CI

Cargo.lock, bin/src/initialize.rs, components/client-pangolin-s2s/Cargo.toml, components/client-pangolin-s2s/src/pangolin.rs, components/client-pangoro-s2s/Cargo.toml, components/client-pangoro-s2s/src/pangoro.rs, components/subscan/src/config.rs, components/subscan/src/types/general.rs, task/task-darwinia-crab/src/fee/strategy/reasonable_strategy.rs, task/task-darwinia-crab/src/task.rs, task/task-pangolin-pangoro/Cargo.toml, task/task-pangolin-pangoro/src/chains/pangolin.rs, task/task-pangolin-pangoro/src/chains/pangoro.rs, task/task-pangolin-pangoro/src/fee/strategy/reasonable_strategy.rs, task/task-pangolin-pangoro/src/service/fee.rs, task/task-pangolin-pangoro/src/service/relay.rs, task/task-pangolin-pangoro/src/task.rs, traits/src/bridge/config.rs
Related: https://github.com/darwinia-network/darwinia-common/pull/959
=> Bump darwinia common to v2.7.0

.github/workflows/release.yml
=> Use Static Openssl

Cargo.lock, bin/Cargo.toml, components/ethereum/Cargo.toml, components/http-client/Cargo.toml, components/shadow/Cargo.toml, components/subscan/Cargo.toml
#349 will solve #338.
Rust TLS is more powerful than native TLS.
But I'll leave this choice(PR) for you.
=> Use Rust TLS

.github/workflows/release.yml, .github/workflows/staging.yml
=> Static openssl support staging environment

.github/workflows/release.yml, .github/workflows/staging.yml
Get rid of libc.so, libssl.so, libz.so...
```
λ ldd target/x86_64-unknown-linux-gnu/release/bridger
not a dynamic executable
```
=> Pure Static Link

task/task-darwinia-ethereum/src/config.rs
Missing configuration. related: #328
=> Add subquery config to bridge darwinia-ethereum

.maintain/release-template.md
https://github.com/darwinia-network/bridger/pull/367
=> Update release changelog

.maintain/release-template.md, Cargo.lock, bin/Cargo.toml, components/client-crab-s2s/Cargo.toml, components/client-darwinia-s2s/Cargo.toml, components/client-darwinia-subxt/Cargo.toml, components/client-pangolin-s2s/Cargo.toml, components/client-pangolin-subxt/Cargo.toml, components/client-pangoro-s2s/Cargo.toml, components/ethereum/Cargo.toml, components/http-client/Cargo.toml, components/shadow/Cargo.toml, components/state/Cargo.toml, components/subscan/Cargo.toml, components/thegraph-liketh/Cargo.toml, primitives/Cargo.toml, supports/support-ethereum/Cargo.toml, supports/support-keep/Cargo.toml, supports/support-proc-macro/Cargo.toml, supports/support-tracker/Cargo.toml, task/linked-darwinia/Cargo.toml, task/linked-template/Cargo.toml, task/task-darwinia-crab/Cargo.toml, task/task-darwinia-ethereum/Cargo.toml, task/task-pangolin-pangoro/Cargo.toml, task/task-pangolin-ropsten/Cargo.toml, task/task-template/Cargo.toml, traits/Cargo.toml
=> Release v0.4.12

task/task-darwinia-ethereum/src/service/darwinia/darwinia_scanner.rs, task/task-darwinia-ethereum/src/service/darwinia/mod.rs, task/task-darwinia-ethereum/src/service/darwinia/scan_schedule_mmr_root_event.rs
=> Fix repeated event(#381)

.maintain/release-template.md, Cargo.lock, bin/Cargo.toml, components/client-crab-s2s/Cargo.toml, components/client-darwinia-s2s/Cargo.toml, components/client-darwinia-subxt/Cargo.toml, components/client-pangolin-s2s/Cargo.toml, components/client-pangolin-subxt/Cargo.toml, components/client-pangoro-s2s/Cargo.toml, components/ethereum/Cargo.toml, components/http-client/Cargo.toml, components/shadow/Cargo.toml, components/state/Cargo.toml, components/subscan/Cargo.toml, components/thegraph-liketh/Cargo.toml, primitives/Cargo.toml, supports/support-ethereum/Cargo.toml, supports/support-keep/Cargo.toml, supports/support-proc-macro/Cargo.toml, supports/support-tracker/Cargo.toml, task/linked-darwinia/Cargo.toml, task/linked-template/Cargo.toml, task/task-darwinia-crab/Cargo.toml, task/task-darwinia-ethereum/Cargo.toml, task/task-pangolin-pangoro/Cargo.toml, task/task-pangolin-ropsten/Cargo.toml, task/task-template/Cargo.toml, traits/Cargo.toml
=> Release v0.4.13

bridges/darwinia-ethereum/bridge/src/service/affirm/mod.rs, bridges/darwinia-ethereum/bridge/src/service/redeem/mod.rs, bridges/pangolin-ropsten/bridge/src/service/affirm/mod.rs, bridges/pangolin-ropsten/bridge/src/service/redeem/mod.rs
=> Remove finished todo comment

bridges/darwinia-ethereum/bridge/src/bridge/message.rs, bridges/darwinia-ethereum/bridge/src/service/redeem/handler.rs, bridges/darwinia-ethereum/bridge/src/service/redeem/mod.rs, bridges/pangolin-ropsten/bridge/src/bridge/message.rs, bridges/pangolin-ropsten/bridge/src/service/redeem/handler.rs, bridges/pangolin-ropsten/bridge/src/service/redeem/mod.rs
#371
Dead code also exists in darwinia-ethereum. This PR is just to make sure the solution is correct.
=> Remove dead code in pangolin-ropsten

frame/components/shadow/src/shadow.rs
Update same with v0.4.13 
https://github.com/darwinia-network/bridger/blob/677fb7860062c07e90083ed5938edef13d1cc58e/components/shadow/src/shadow.rs#L69
=> Try fix shadow response code check

bridges/darwinia-ethereum/bridge/src/service/guard.rs, bridges/pangolin-ropsten/bridge/src/service/guard.rs
=> Fix bridger-242 Repeat guard voting

bridges/darwinia-ethereum/Cargo.lock, bridges/darwinia-ethereum/bridge/Cargo.toml, bridges/darwinia-ethereum/bridge/src/bridge/message.rs, bridges/darwinia-ethereum/bridge/src/service/extrinsics/handler.rs, bridges/darwinia-ethereum/bridge/src/service/extrinsics/mod.rs, bridges/pangolin-ropsten/Cargo.lock, bridges/pangolin-ropsten/bridge/Cargo.toml, bridges/pangolin-ropsten/bridge/src/bridge/message.rs, bridges/pangolin-ropsten/bridge/src/service/extrinsics/handler.rs, bridges/pangolin-ropsten/bridge/src/service/extrinsics/mod.rs, frame/supports/support-ethereum/src/mmr.rs, frame/supports/support-ethereum/src/receipt.rs
=> Fix bridger-288 Lost extrinsics  data when bridger restart

bridges/darwinia-ethereum/Cargo.lock, bridges/pangolin-ropsten/Cargo.lock, frame/supports/support-command-kv/Cargo.toml, frame/supports/support-command-kv/src/handler.rs, frame/supports/support-command-kv/src/schema.toml
=> bridger-377 Wrap schema for KV database to support cli command

.maintain/config/bridge-darwinia-crab.toml, bridges/darwinia-crab/Cargo.lock, bridges/darwinia-crab/Cargo.toml, bridges/darwinia-crab/bridge/Cargo.toml, bridges/darwinia-crab/bridge/src/bridge/config.rs, bridges/darwinia-crab/bridge/src/chains/crab.rs, bridges/darwinia-crab/bridge/src/chains/darwinia.rs, bridges/darwinia-crab/bridge/src/chains/mod.rs, bridges/darwinia-crab/bridge/src/command/handler/init.rs, bridges/darwinia-crab/bridge/src/service/relay.rs, bridges/darwinia-crab/bridge/src/types.rs, bridges/darwinia-crab/client-crab/Cargo.toml, bridges/darwinia-crab/client-crab/src/api.rs, bridges/darwinia-crab/client-crab/src/crab.rs, bridges/darwinia-crab/client-darwinia/Cargo.toml, bridges/darwinia-crab/client-darwinia/src/api.rs, bridges/darwinia-crab/client-darwinia/src/darwinia.rs, bridges/pangolin-pangoro/bridge/src/types.rs
Related:
https://github.com/darwinia-network/darwinia-bridges-substrate/pull/13
=> Update bridge darwinia-crab

subql/parachain/kusama/src/helpers/constants.ts, subql/parachain/rococo/src/helpers/constants.ts
=> Correct para id

.github/workflows/release.yml
=> fix: rename release package

.github/workflows/subgraph-dev.yml, .github/workflows/subgraph-mmr.yml, .github/workflows/subgraph-prod.yml, .github/workflows/subquery-dev.yml, .github/workflows/subquery-prod.yml
- Change production mode to manually deploy 
- Deploy develop mode to another subql project
Related: https://github.com/darwinia-network/bridger/pull/444#issuecomment-1085403327
=> Refactor subql CI

.maintain/config/bridge-darwinia-ethereum.toml, .maintain/config/bridge-pangolin-ropsten.toml, bridges/pangolin-ropsten/Cargo.lock, bridges/pangolin-ropsten/bridge/src/command/handler/confirm.rs, bridges/pangolin-ropsten/bridge/src/command/handler/guard.rs, bridges/pangolin-ropsten/bridge/src/service/check.rs, bridges/pangolin-ropsten/bridge/src/service/extrinsics/handler.rs, bridges/pangolin-ropsten/client-pangolin/Cargo.toml, bridges/pangolin-ropsten/client-pangolin/src/client.rs, bridges/pangolin-ropsten/client-pangolin/src/config.rs, bridges/pangolin-ropsten/client-pangolin/src/error.rs, bridges/pangolin-ropsten/client-pangolin/src/ethereum/api.rs, bridges/pangolin-ropsten/client-pangolin/src/types/account.rs, bridges/pangolin-ropsten/client-pangolin/src/types/patch.rs
Bump subxt version for bridge pangolin-ropsten and make some changes follow #434
=> Update bridge pangolin ropsten

subql/s2s/pangolin-parachain/examples/need_relay_block.query.txt, subql/s2s/pangolin-parachain/schema.graphql, subql/s2s/pangolin-parachain/src/handler/block.ts, subql/s2s/pangolin-parachain/src/handler/event.ts, subql/s2s/pangolin-parachain/src/helpers/block.ts, subql/s2s/pangolin-parachain/src/mappings/mappingHandlers.ts, subql/s2s/pangolin-parachain/src/storage/block.ts, subql/s2s/pangolin-parachain/src/storage/event.ts, subql/s2s/pangolin-parachain/src/storage/index.ts, subql/s2s/pangolin/examples/need_relay_block.query.txt, subql/s2s/pangolin/schema.graphql, subql/s2s/pangolin/src/handler/block.ts, subql/s2s/pangolin/src/handler/event.ts, subql/s2s/pangolin/src/helpers/block.ts, subql/s2s/pangolin/src/mappings/mappingHandlers.ts, subql/s2s/pangolin/src/storage/block.ts, subql/s2s/pangolin/src/storage/event.ts, subql/s2s/pangolin/src/storage/index.ts, subql/s2s/rococo/examples/need_relay_block.query.txt, subql/s2s/rococo/schema.graphql, subql/s2s/rococo/src/handler/block.ts, subql/s2s/rococo/src/handler/event.ts, subql/s2s/rococo/src/helpers/block.ts, subql/s2s/rococo/src/mappings/mappingHandlers.ts, subql/s2s/rococo/src/storage/block.ts, subql/s2s/rococo/src/storage/event.ts, subql/s2s/rococo/src/storage/index.ts
Related: #449 
query
```
query queryNeedRelayBlockPage {
justificationMappings (
first: 5
orderBy: BLOCK_NUMBER_DESC
) {
nodes {
id
blockNumber
blockHash
mandatory
justification
}
}
needRelayBlocks (
first: 5
orderBy: BLOCK_NUMBER_ASC
) {
nodes {
id
blockNumber
blockHash
type
origin
laneId
messageNonce
timestamp
}
}
}
```
response
```
{
"data": {
"justificationMappings": {
"nodes": [
{
"id": "1094519",
"blockNumber": 1094519,
"blockHash": "0x54f429c5a10222781a89a62d61ba2c501a266b6a85328f0b55a6652d50474a26",
"mandatory": true,
"justification": "0x200500000000000054f429c5a10222781a89a62d61ba2c501a266b6a85328f0b55a6652d50474a2677b310000c54f429c5a10222781a89a62d61ba2c501a266b6a85328f0b55a6652d50474a2677b3100005988192f02868246e153bb3610fc044682aa5161ff66a8f9b21dac983bf80e526ec9811b7f86dfc736b88 …
```
=> Optimize subql bridge parachain

subql/parachain/rococo/project.yaml, subql/s2s/pangolin-parachain/src/storage/event.ts, subql/s2s/pangolin/project.yaml, subql/s2s/pangolin/src/storage/event.ts, subql/s2s/rococo/project.yaml, subql/s2s/rococo/src/storage/event.ts
=> Fix subql null error

bridges/pangolin-pangolinparachain/Cargo.lock, bridges/pangolin-pangolinparachain/bridge/Cargo.toml, bridges/pangolin-pangolinparachain/bridge/src/bridge/task.rs, bridges/pangolin-pangolinparachain/bridge/src/service/header/pangolin_to_parachain.rs, bridges/pangolin-pangolinparachain/bridge/src/service/header/para_head_to_pangolin.rs, bridges/pangolin-pangolinparachain/bridge/src/service/header/rococo_to_pangolin.rs, bridges/pangolin-pangolinparachain/bridge/src/service/message.rs, bridges/pangolin-pangolinparachain/bridge/src/service/mod.rs, bridges/pangolin-pangolinparachain/bridge/src/service/subscribe.rs, bridges/pangolin-ropsten/Cargo.lock, frame/assistants/client-pangolin-parachain/src/component.rs, frame/assistants/client-pangolin/Cargo.toml, frame/assistants/client-pangolin/src/client.rs, frame/assistants/client-pangolin/src/error.rs, frame/assistants/client-pangolin/tests/test_component.rs, frame/assistants/client-pangoro/src/component.rs, frame/assistants/client-rococo/Cargo.toml, frame/assistants/client-rococo/src/client.rs, frame/assistants/client-rococo/src/component.rs, frame/assistants/client-rococo/src/error.rs, frame/assistants/subquery-parachain/src/graphql/generic/next_candidate_included_event_with_para_head.query.graphql, frame/assistants/subquery-parachain/src/subquery.rs, frame/assistants/subquery-parachain/src/types/subquery.rs, frame/assistants/subquery-s2s/src/graphql/generic/next_needed_header.query.graphql, frame/assistants/subquery-s2s/src/subquery.rs, frame/assistants/subquery-s2s/src/types/s2s.rs, frame/assistants/subquery-s2s/src/types/subquery.rs, subql/s2s/pangolin/src/handler/event.ts
1. Header relay on demand
2. Subscribe to grandpa justification, an optimization that could accelerate relaying headers.
=> On demand header relay

bridges/darwinia-crab/bridge/src/feemarket/crab.rs
The Feemarket pallet is changed to DarwiniaFeemarket
=> Rename Feemarket to DarwiniaFeemarket

frame/assistants/client-crab-parachain/src/fastapi/bridge_s2s/bridge_crab.rs, frame/assistants/client-crab/src/fastapi/bridge_s2s/bridge_crabparachain.rs, frame/assistants/client-crab/src/fastapi/bridge_s2s/bridge_darwinia.rs, frame/assistants/client-darwinia/src/fastapi/bridge_s2s/bridge_crab.rs, frame/assistants/client-pangolin-parachain/src/fastapi/bridge_s2s/bridge_pangolin.rs, frame/assistants/client-pangolin/src/fastapi/bridge_s2s/bridge_pangolinparachain.rs, frame/assistants/client-pangolin/src/fastapi/bridge_s2s/bridge_pangoro.rs, frame/assistants/client-pangoro/src/fastapi/bridge_s2s/bridge_pangolin.rs, frame/assistants/relay-s2s/src/header/relaychain_head_relay.rs, frame/assistants/relay-s2s/src/header/solochain_head_relay.rs, frame/assistants/relay-s2s/src/keepstate.rs, frame/assistants/relay-s2s/src/message/common/delivery_relay.rs, frame/assistants/relay-s2s/src/message/common/receiving_relay.rs, frame/supports/support-common/src/initialize.rs
fix https://github.com/darwinia-network/bridger/issues/482
=> Improve s2s bridge

bridges/crab-crabparachain/bridge/src/service/header/kusama_to_crab.rs, frame/assistants/client-crab-parachain/src/fastapi/bridge_s2s/bridge_crab.rs, frame/assistants/subquery-s2s/src/graphql/generic/query_need_relay.graphql
- add on-demand type for delivery index query
- fix wrong bridge crab-crabparachain origin type
=> fix bug for bridge s2s

bridges/crab-crabparachain/Cargo.lock, bridges/darwinia-crab/Cargo.lock, bridges/darwinia-ethereum/Cargo.lock, bridges/pangolin-pangolinparachain/Cargo.lock, bridges/pangolin-pangolinparachain/bridge/Cargo.toml, bridges/pangolin-pangoro/Cargo.lock, bridges/pangolin-ropsten/Cargo.lock, bridges/pangolin-ropsten/bridge/src/service/extrinsics/handler.rs, bridges/pangoro-chapel/Cargo.lock, frame/assistants/README.md, frame/assistants/client-crab-parachain/Cargo.toml, frame/assistants/client-crab/Cargo.toml, frame/assistants/client-darwinia/Cargo.toml, frame/assistants/client-kusama/Cargo.toml, frame/assistants/client-pangolin-parachain/Cargo.toml, frame/assistants/client-pangolin/Cargo.toml, frame/assistants/client-pangolin/src/fastapi/ethereum.rs, frame/assistants/client-pangolin/src/subxt_runtime/runtime.rs, frame/assistants/client-pangolin/src/types/patch.rs, frame/assistants/client-pangoro/Cargo.toml, frame/assistants/client-rococo/Cargo.toml, frame/assistants/relay-s2s/Cargo.toml, frame/traits/bridge-s2s/Cargo.toml, frame/traits/feemarket-s2s/Cargo.toml
- Bump substrate to darwinia-v0.12.4
- Update ethv1 bridge (pangolin-ropsten) follow https://github.com/darwinia-network/darwinia-common/pull/1335 https://github.com/darwinia-network/darwinia-common/pull/1337
=> Update bridge pangolin-ropsten

.maintain/config/bridge-pangoro-kiln.toml, bridges/pangoro-kiln/Cargo.lock, bridges/pangoro-kiln/bridge/Cargo.toml, bridges/pangoro-kiln/bridge/src/bridge/config.rs, bridges/pangoro-kiln/bridge/src/bridge/task.rs, bridges/pangoro-kiln/bridge/src/kiln_client/client.rs, bridges/pangoro-kiln/bridge/src/kiln_client/message_client.rs, bridges/pangoro-kiln/bridge/src/kiln_client/mod.rs, bridges/pangoro-kiln/bridge/src/kiln_client/types.rs, bridges/pangoro-kiln/bridge/src/main.rs, bridges/pangoro-kiln/bridge/src/message_contract/FeeMarket.json, bridges/pangoro-kiln/bridge/src/message_contract/Inbound.json, bridges/pangoro-kiln/bridge/src/message_contract/Outbound.json, bridges/pangoro-kiln/bridge/src/message_contract/fee_market.rs, bridges/pangoro-kiln/bridge/src/message_contract/inbound.rs, bridges/pangoro-kiln/bridge/src/message_contract/message_client.rs, bridges/pangoro-kiln/bridge/src/message_contract/mod.rs, bridges/pangoro-kiln/bridge/src/message_contract/outbound.rs, bridges/pangoro-kiln/bridge/src/pangoro_client/client.rs, bridges/pangoro-kiln/bridge/src/service/header_relay/execution_layer_update.rs, bridges/pangoro-kiln/bridge/src/service/header_relay/kiln_to_pangoro.rs, bridges/pangoro-kiln/bridge/src/service/header_relay/sync_committee_update.rs, bridges/pangoro-kiln/bridge/src/service/message_relay/kiln_to_pangoro.rs, bridges/pangoro-kiln/bridge/src/service/message_relay/mod.rs, bridges/pangoro-kiln/bridge/src/service/mod.rs
Message relay from Sepolia to Pangoro:
```
2022-07-28 08:13:23  INFO pangoro-kiln: [MessageDelivery][Kiln => Pangoro] Last delivered nonce is 6, equal to lastest generated. Do nothing.
2022-07-28 08:13:24  INFO pangoro-kiln: [ExecutionLayer][Kiln => Pangoro] Latest execution payload state root at slot 271744 is : 0x1ef8a5355046e6bcd8f75055a2d878936d76e4e44234c5b2f74f4ceaf8f7235e
2022-07-28 08:13:24  INFO pangoro-kiln: [Header][Kiln => Pangoro] State: HeaderRelayState { relayed_slot: 271744, relayed_period: 33, current_slot: 271866, current_period: 33 }
2022-07-28 08:13:24  INFO pangoro-kiln: [SyncCommittee][Kiln => Pangoro] Next sync committee is 0xfa3b023b07267fc3e66406c6771fe92b1a47a57b83b9191303594458280c9902
2022-07-28 08:13:35  INFO pangoro-kiln: [Header][Kiln => Pangoro] State: …
```
=> Message relay ETH=>Pangoro

.maintain/config/bridge-crab-crabparachain.toml, .maintain/config/bridge-darwinia-crab.toml, .maintain/config/bridge-pangolin-pangolinparachain.toml, .maintain/config/bridge-pangolin-pangoro.toml, bridges/crab-crabparachain/bridge/src/bridge/config.rs, bridges/crab-crabparachain/bridge/src/service/header/crab_to_parachain.rs, bridges/crab-crabparachain/bridge/src/service/header/kusama_to_crab.rs, bridges/darwinia-crab/bridge/src/bridge/config.rs, bridges/darwinia-crab/bridge/src/service/header/crab_to_darwinia.rs, bridges/darwinia-crab/bridge/src/service/header/darwinia_to_crab.rs, bridges/pangolin-pangolinparachain/bridge/src/bridge/config.rs, bridges/pangolin-pangolinparachain/bridge/src/service/header/pangolin_to_parachain.rs, bridges/pangolin-pangolinparachain/bridge/src/service/header/rococo_to_pangolin.rs, bridges/pangolin-pangoro/bridge/src/bridge/config.rs, bridges/pangolin-pangoro/bridge/src/service/header/pangolin_to_pangoro.rs, bridges/pangolin-pangoro/bridge/src/service/header/pangoro_to_pangolin.rs, frame/assistants/relay-s2s/src/header/relaychain_head_relay.rs, frame/assistants/relay-s2s/src/header/solochain_head_relay.rs, frame/assistants/relay-s2s/src/types.rs
Provides an option whether to perform mandatory header relay.
=> Optional mandatory header relay

bridges/darwinia-ethereum/bridge/src/service/darwinia/scan_authorities_change_signed_event.rs, bridges/pangolin-ropsten/bridge/src/service/pangolin/scan_authorities_change_signed_event.rs, frame/assistants/README.md, frame/assistants/client-darwinia/src/fastapi/ethereum.rs, frame/assistants/client-darwinia/src/subxt_runtime/runtime.rs, frame/assistants/client-darwinia/src/types/patch.rs, frame/assistants/client-pangolin/src/fastapi/ethereum.rs
Related:
- https://github.com/darwinia-network/darwinia/pull/936
=> Update ecdsa relay pallet name for bridge darwinia-ethereum

frame/assistants/README.md, frame/assistants/client-pangolin/src/subxt_runtime/runtime.rs
=> Update feemarket storage key

assistants/bin-e2e/src/task.rs
This PR(https://github.com/darwinia-network/bridger/pull/555) didn't take the config into account, and here is the fix.
=> Fix general config

assistants/client-crab/src/fastapi/feemarket_s2s/generic.rs, assistants/client-darwinia/src/fastapi/feemarket_s2s/generic.rs, assistants/client-pangoro/src/fastapi/feemarket_s2s/generic.rs, assistants/feemarket-s2s/src/relay/basic.rs, frame/traits/feemarket-s2s/src/api.rs
Based on #553 
Only relay messages when the order is in the assigned relayer's slot
=> Improve feemarket strategy

state/.gitignore, state/src/data/chain_info.js
- fix wrong icon link for darwinia and crab
- fix wrong endpoint for beacon chain
=> Fix bridge state

.github/workflows/ci.yml, .github/workflows/release.yml, .maintain/config/bridge-darwinia-crab.toml, README.md, assistants/client-crab/Cargo.toml, assistants/client-crab/src/fastapi/bridge_s2s/bridge_darwinia_crab.rs, assistants/client-darwinia/Cargo.toml, assistants/client-darwinia/src/fastapi/bridge_s2s/bridge_darwinia_crab.rs, assistants/client-kusama/Cargo.toml, assistants/client-moonbase/Cargo.toml, assistants/client-pangolin/Cargo.toml, assistants/client-pangoro/Cargo.toml, assistants/client-polkadot/Cargo.toml, assistants/client-rococo/Cargo.toml, assistants/ecdsa-pair/Cargo.toml, assistants/feemarket-s2s/src/relay/basic.rs, assistants/relay-s2s/Cargo.toml, bridges/darwinia-crab/Cargo.lock, bridges/pangolin-pangoro/Cargo.lock, bridges/pangolin-pangoro/docs/Guide.md, traits/bridge-e2e/Cargo.toml, traits/bridge-s2s/Cargo.toml, traits/client-common/Cargo.toml, traits/feemarket-s2s/Cargo.toml
- bridge darwinia-crab
- bump deps
- fix #576 
- fix #575
=> Bridge darwinia-crab
